# SITE CONFIGURATION
baseurl: 
url: "https://agu-data.github.io"

# THEME-SPECIFIC CONFIGURATION
title: AGU Data Leadership                                # site's title
description: "Earth and space sciences data and software resources."      # used by search engines
avatar: assets/img/agu-trademark-logo.png                        # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: AGU Data Leadership   # Change Blog header text
header_feature_image: assets/img/pexels/AGU-Stock-Nasa-Satellite-water-1314x400.jpg
footer_text: >
  A community resource powered by <a href="https://www.agu.org/Learn-About-AGU/About-AGU/Data-Leadership">AGU Data Leadership</a>.

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics: "UA-199542898"                        # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# RESOURCES
collections:
  resources:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
